### ISSUE TITLE
not compatible the latest goland (2021.3)

### ISSUE THREAD

**Issue by jiangtao244** [ExidCuter/docker-registry-explorer-plugin#1]
Plugin error: Plugin 'Docker Registry Explorer' (version '1.0.2-stable') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is GO-211.6693.119

**Comment by ExidCuter** [comment]
The update has been submitted to the JetBrains Marketplace and should be available after their review process is completed.
