### ISSUE TITLE
synchronous fetch of registry info locks ide

### ISSUE THREAD

**Issue by andybrown668** [ExidCuter/docker-registry-explorer-plugin#10]
When I start my ide or click on a registry then ide becomes unresponsive for maybe 30/45 seconds until the plugin has completed fetching/refreshing its state. 
I just installed the plugin with current Goland 2021.2.4 but it's unusable because of this.

**Comment by ExidCuter** [comment]
Hi, sorry for the late response. I work on this in my spare time an as of recent I had very little of that.

About the issue. Did you try to install a newer/older version of Goland? How many registries are you connected to?

For me it works fine in Goland 2021.3.1.
