### ISSUE TITLE
Error while connecting to Docker Hub

### ISSUE THREAD

**Issue by Ziggizag** [ExidCuter/docker-registry-explorer-plugin#13]
Hi,

I wanted to try you Docker Registry Explorer but O always get this error:
![image](https://user-images.githubusercontent.com/2280036/179260599-c067cab7-fab2-461a-8242-1c149f8185fd.png)

![image](https://user-images.githubusercontent.com/2280036/179260649-b56c1c62-e268-48b8-8228-aec46152082e.png)

**Comment by ExidCuter** [comment]
Hi, this plugin is meant for private self hosted Docker registries. That is why it will not work with the public Docker Hub registry.
