### ISSUE TITLE
Add support for PyCharm 2022.3

### ISSUE THREAD

**Issue by hansingt** [ExidCuter/docker-registry-explorer-plugin#14]
First of all, thanks for the great plugin.

I've updated recently to the latest version of PyCharm (2022.3) and now, it says that the plugin would not be compatible with it
as it requires `IDE builds 222.* or earlier`.

Would it be possible to add support for the latest PyCharm / IntelliJ-Based IDEs as well?

**Comment by ExidCuter** [comment]
Update has been accepted by JetBrains. So now you can update the plugin inside your IDE.
