### ISSUE TITLE
Requires IDE Build 211.* or older

### ISSUE THREAD

**Issue by raarts** [ExidCuter/docker-registry-explorer-plugin#6]
See the subject line. This is the error I get now with the newest PHP Storm. Using #WS-212.4746.80

**Comment by ExidCuter** [comment]
The update has been submitted to the JetBrains Marketplace and should be available after their review process is completed. In the meantime you can download latest version from [here](https://github.com/ExidCuter/docker-registry-explorer-plugin/releases/tag/1.0.6-stable).
